### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by wincowgerDEV** [hsherrod2019/Week4RepoReal#1]
- The readme is thorough and follows what elements I would expect for an R package. 
- You probably want to put raman_hpde.csv into another folder labeled data so that people know where they can look for supporting data. There are also ways you can integrate the data as something that can be called in the R Package https://www.youtube.com/watch?v=BHgNA1vJO_0
- The installation instructions should include instructions how to install your R package using github and installation should probably come first in the readme. https://github.com/hsherrod2019/Week4RepoReal/tree/main#installation
- Your instructions on use should show the user how to use your functions by calling your package instead of by calling the function. If you call the function, you could overwrite the package function and things get messy because of name conflicts. https://github.com/hsherrod2019/Week4RepoReal/tree/main#my-r-package
- Your function examples in the help pane should be able to run with minimal intervention by the user. Currently if I copy and pasted your function into R with your library loaded I wouldn't get the output that I think you are looking for. At least not for the calculate_average_intensity or the calculate_average_wavenumber. The calculate_intensity_ratio seems to work. 
- Let's meet up later this week and go over some of the package installation, build, and function concepts. It will probably be easier for me to show you in person how these interactions are happening. 
- Thanks for the hard work!

**Comment by wincowgerDEV** [comment]
meant to mention you @hsherrod2019

**Comment by hsherrod2019** [comment]
Thank you @wincowgerDEV ! I just finished updating the repo and R package with those changes. Yes, that'll be great to meet up later this week to go over those concepts.

**Comment by wincowgerDEV** [comment]
Thanks @hsherrod2019, great work!
